# Generated by Django 5.0.3 on 2024-03-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoteleraApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HoteleraApp.hotel'),
        ),
    ]
